name: Linux (clang)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: "Setup required packages"
        run: |
          sudo ./pkg-dependency.sh

      - name: "Setup clangd"
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x ./llvm.sh
          sudo ./llvm.sh 16

      - name: "Setup cmake"
        run: cmake --version

      - name: "Setup git submodule"
        run: git submodule update --init --recursive

      - name: "Build and test"
        run: |
          export CC=clang-16
          export CXX=clang++-16
          mkdir build.debug && cd build.debug
          cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..
          ninja memory_test
          ./test/memory_test
