name: Linux (gcc)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: "Setup required packages"
        run: sudo ./pkg-dependency.sh

      - name: "Setup cmake"
        run: cmake --version

      - name: "Setup git submodule"
        run: git submodule update --init --recursive

      - name: "Build and test"
        run: |
          export CC=gcc-14
          export CXX=g++-14
          mkdir build.debug && cd build.debug
          cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..
          ninja memory_test
          ./test/memory_test
